### PR TITLE
Turkish language support.

### PR DESCRIPTION
**Pull request by ghost**
Request to add Turkish language support. Except for a few translations, I'm mostly happy with it.

### CODE REVIEW

**Comment by jshipley** [comment]
It looks like there's a lot of text (messages, tooltips, etc.) using Text.literal() and Text.of(). I'm working on a PR to make all of those translatable, so this should need some more translations to be done.

I'll submit the PR later this evening.

**Comment by Rearth** [comment]
Huge thanks for the translation, it's always appreciated. Since some of the texts arent translatale yet, I'll leave this PR open for now. @jshipley Are you already working on improving the text.literal calls? If not please let me know, then I'll get started on this

**Comment by jshipley** [comment]
Yes, I've been working on it. I have everything translatable now, but I still need to review/test everything.

There were a few things that I tried that aren't working (interpolation in a "translated" key doesn't seem to do anything, and I can't find any documentation about it at all), so I'm going to have to simplify things and redo those bits.

It's probably about 80% right now.

**Comment by Rearth** [comment]
Hi @FourPandora2112 , translations are now possible, and we just added chinese translations. Feel free to update this PR with the updated lang files, and I'll be happy to merge it

**Pull request closed without merging**
