### PR TITLE
The first version of the Polish language

### PR DESCRIPTION
**Pull request by plhappylemonpl**
use to translate:

my brain KEKW
google translate
chat gpt

Files that I haven't translated yet, but it's already late 2;17 am in Poland xD:

Oritech\src\main\resources\assets\oritech\lavender\entries\oritech_guide\pl_pl\resources\

crude_oil.md
duratium.md
electrum.md
enderic_compound.md
energite.md
fluxite.md
nickel.md
ore_boulder.md
platinum.md
prometheum.md
resource_node.md
silicon.md
steel.md

### CODE REVIEW

**Comment by PrzemolPL** [comment]
I recommend this user 😁

**Comment by Rearth** [comment]
Huge thanks for the translation already. I'm working on some internal refactoring atm and will merge the PR when the refactoring is done.

**Comment by Rearth** [comment]
Hi, huge thanks for the PR. This is looking mostly good. One thing before merging: I updated the main branch to architectury, and with that the file locations have changed. Can you update the folders accordingly (or just update your branch from main)? The new path should be common/src/main/resources/...

**Comment by plhappylemonpl** [comment]
pl_PL

**Pull request merged**
