### PR TITLE
zh-CN Translation

### PR DESCRIPTION
**Pull request by OakPlatinum**
This PR contains about 90% part of the localization file translated. Book hasn't been translated and will be done in one month or longer.

Hmm, @Rearth could you create a localization project on Crowdin? It will make translation much more convenient. I'd appreciate if you could consider this.
Also, well, how to translate the instruction book? I read its wiki, and can't find anything about localization.

### CODE REVIEW

**Comment by Rearth** [comment]
Hi, huge thanks for the translation. I'll also take a look at creating a project on CrowndIn very soon, great idea. I'd prefer to wait till the whole translation file is finished before merging this. We don't need the book in the initial PR I think. To translate the book I didn't find anything in the lavender docs, but found this in their discord:

**Comment by Rearth** [comment]
image

**Comment by OakPlatinum** [comment]
OK. Thank you for helping me with my question. I just finished all translations, and you can merge it now.

**Review by Rearth — APPROVED** [review]

**Comment by Rearth** [comment]
Huge thanks, this is looking great. Do you want me to merge the PR already or are you still actively working on the book translations? We could also do those in a separate PR if you want

**Comment by OakPlatinum** [comment]
Just merge it; those commits are a test.

I'll open another draft PR for the whole book translation.

You're welcome, @Rearth ;)

**Pull request merged**
