### PR TITLE
tr_tr.json Turkish Localization

### PR DESCRIPTION
**Pull request by RuyaSavascisi**

### CODE REVIEW

**Comment by OakPlatinum** [comment]
Well, actually you can submit it on [Crowdin](https://crowdin.com/project/oritech).
Do you mind translating the guidebook as well? Thank you so much for your contribution!

**Comment by RuyaSavascisi** [comment]
Np. Can't find Turkish language in Crowdin. When i have free time i can translate the guidebook too with pleasure ^^

**Comment by OakPlatinum** [comment]
Yeah, I'll ask Rearth so that he would add Turkish soon.

**Comment by Rearth** [comment]
Hi, huge thanks for the translation. I'll merge this for now. We can always do the guide book later. I'll also add the language to crowdin so we can manage it there later.

**Pull request merged**
