### PR TITLE
Adding some recipes for Mythic Metals compatibility

### PR DESCRIPTION
**Pull request by jshipley**
For #92

Added compatibility recipes for Mythic Metals and moved Alloy Forgery compatibility recipes into datagen.

### CODE REVIEW

**Comment by OakPlatinum** [comment]
Great! Thank you!
Btw could you add "close #92" in the commit message so it automatically closes that issue?

**Comment by Rearth** [comment]
This is looking great, thanks for all the worr that went into this. When merging i'll adjust the message to close the issue with this. One more thing before merging: Is there a way to only include those mobs in datagen, and maybe turn them on and off when actually running the dev environment? I don't want to have all  compat mods active when working on the mod, and having to manually enable them and reload gradle before each datagen also doesnt seem right?

**Comment by jshipley** [comment]
I'll see if I can add the dependencies in a datagen run configuration.

**Comment by jshipley** [comment]
That was easy. I tried adding a dependencies block inside of configureDataGeneration and the datagen is still able to run. It also makes it more obvious what the dependencies are for and prevents anything else from accidentally relying on them.

**Comment by Rearth** [comment]
Thanks, this is looking cleaner already. I'll go ahead and merge it

**Pull request merged**
