### PR TITLE
Translation to german

### PR DESCRIPTION
**Pull request by ghost**
This is a small step towards complete translation, with about 27 % of the de_de.json now translated. 
Some lines that are done will have to be reworked later, but first I want to focus on getting the full file translated.

### CODE REVIEW

**Comment by Rearth** [comment]
Hi, is it okay with you if I wait with merging till the whole file is translated?

**Comment by ghost** [comment]
Sure, ' had not much time in the past days. I am now going to work further on it.

**Comment by ghost** [comment]
I am about 80% done now. I hope I'll get to the rest tomorrow.

**Comment by ghost** [comment]
This should be done now, for now.

**Comment by Rearth** [comment]
Great, huge thanks. I'll include it in the next update

**Pull request merged**
